import os
import sys
import operator

if (len(sys.argv) >= 2):
    seqfiledir = sys.argv[1]
else:
    seqfiledir = input("Enter path to sequence file directory (containing sequence files initially generated by bedtools): ")

if (not os.path.isdir(seqfiledir)):
    print("Path \"", seqfiledir, "\" is not an existing directory. Exiting...\n", sep='')
    exit(1)

for file in os.listdir(seqfiledir):
    filename = os.fsdecode(file)
    filename_noext = os.path.splitext(filename)[0]

    filepath = os.path.join(seqfiledir, filename)

    if (os.path.isfile(filepath) and filepath.endswith(".txt") and not filepath.endswith("_trimmed.txt")):
        with open(filepath, "r") as src:

            outfpath = filename_noext + "_trimmed.txt"
            outfpath = os.path.join(seqfiledir, outfpath)

            print("Creating output file \"", outfpath, "\"...", sep="")
            with open(outfpath, "w") as outfile:
            
                for line in src:
                    if (line[0] != '>'):
                        outfile.write(str(line).upper())
                
                src.close()
                outfile.close()

                os.remove(os.path.join(seqfiledir,file))

    else:
        print("File \"", filepath, "\" cannot be determined to be a valid nucleotide sequence file or is already trimmed\n", sep='')